include ../Makefile

IN = in.asm
OUT = out.obj
IO_FILES = $(IN) $(OUT)
OUT_EXE = lab1
DEBUG_EXE = lab1debug
TURNIN_OUTFILE = assembler.c
TURNIN_OUTDIR = turnin

#go: build
#	./$(OUT_EXE) $(IO_FILES)

